services:
  - type: web
    name: tbmedia
    env: node
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: CACHE_TTL_CATALOG
        value: "3600"
      - key: CACHE_TTL_STREAM
        value: "21600"
      # Opcional: Adicione variáveis do Redis se precisar de cache persistente no Render
      # - key: REDIS_URL
      #   value: "..."
